apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-app-svc
spec:
  type: LoadBalancer
  selector:
    app: ping-pong-app
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 9090