apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: database-configmap
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS todos (
    id SERIAL PRIMARY KEY,
    todo VARCHAR(140) NOT NULL
    );
  POSTGRES_DB: "tododb"
  POSTGRES_USER: "todouser"