apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app-deployment
  labels:
    app: log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: log-app-write
          image: dxvann/log-output-write:1.11
          env:
            - name: LOG_OUT_FILE_PATH
              value: "/usr/src/app/files/uuid.txt"
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
        - name: log-app-read
          image: dxvann/log-output-read:1.11
          env:
            - name: PING_PONG_FILE_PATH
              value: "/usr/src/app/files/count.txt"
            - name: LOG_OUT_FILE_PATH
              value: "/usr/src/app/files/uuid.txt"
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files

        