apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: log-app-svc
spec:
  type: ClusterIP
  selector:
    app: log-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 9090